sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tByr7QwmoyNUiQiv3dn
    access-key-secret: yY44IBnJ2mORZvIcA15Q1BH7rX8AmN
    bucket-name: testcommon

  redis:
    host: localhost
    port: 6379
