sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234


  redis:
    host: localhost
    port: 6379
  wechat:
    appid: wx487f0798653ed1b1
    secret: 3043933b5a0942e928e90752fa0dca0c
    mchid: 1551414330
    mchSerialNo: 1554654464AAAdsd
    privateKeyFilePath: D:\lljl
    apiV3Key: hhugyibyiuu
    weChatPayCertFilePath: D:\lljl
    notifyUrl: https://weewf
    refundNotifyUrl: https://weewf

  alioss:
    access-key-id: LTAI5tPeFLzPPT8gG3LPW64
    access-key-secret: U6k1brOZ8gaOIXv3nXbu1GTUzy6Pd7
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: sky-itcast

